### ISSUE TITLE
Running error because the negative_lits_map*.json and positive_lits_map*.json not exists

### ISSUE THREAD

**Issue by Gy-Hu** [nhamlv-55/Ropey#1]
Hi,
I am trying to reproduce the result, but I encounter the issue after I configure the environment and run the command in README.md. The issue happens when it loads `lits_map` . However, those file ( `negative_lits_map*.json` and `positive_lits_map*.json` ) are not included in the dataset folder (which is located in `grpc_test_runs/chc0002/ind_gen_files/` ). May I know how to generate those file? Thanks!

If you clone the repository of master branch, you can easily reproduce this error.

![image](https://user-images.githubusercontent.com/43922980/147230648-8d95b38b-ed14-4f42-96e3-bfb39f6d9065.png)

**Comment by nhamlv-55** [comment]
Ouch. Let me check in missing files. Thanks for letting me know!

**Comment by nhamlv-55** [comment]
Hello @Gy-Hu , we have updated the master branch with the needed files, as well as our README. Could you please give it another try? If there are more issues, please let me know!
Thanks a lot!

**Comment by Gy-Hu** [comment]
Thanks for your reply! I have no time to check right now, but I will give you the new feedback if I could not run it successfully. Congrats to your paper acceptance in FMCAD 2021! This is an interesting work.
