### ISSUE TITLE
error occurs in total_loss.backward()

### ISSUE THREAD

**Issue by Gy-Hu** [nhamlv-55/Ropey#4]
Hi,
I pull the latest code in master branch, and fix the path issue. However, it still has some problems. The problem occurs on line 132 in `RNN_train.py` 

```python
for dataObj in dataObjs:
    last_batch = False
    n_dps = 0
    optimizer.zero_grad()
    total_loss = 0
    while not last_batch:
        train, last_batch = dataObj.next_batch(dataObj.train_dps, 1, configs['gamma'][0])

        if train is not None:
            labels = train["labels"][0]
            # print("labels", labels, labels.size())

            output = model(train["input_trees"][0])

            loss = loss_function(output, labels)
            #loss.backward()
            total_loss += loss
            n_dps+=1
    total_loss.backward() <----------------------------- problem occurs when run to this line
```
I guess this issue may related to my pytorch version, which is `1.2.0` . May I know your conda environment or pip environment (with the exact version of package) ?

![image](https://user-images.githubusercontent.com/43922980/147665221-447f8d87-8c93-4a80-8bc6-79d763e46332.png)

**Comment by nhamlv-55** [comment]
Hello @Gy-Hu 
Thanks for reporting the issue. Yes I believe this is a version issue. I have pushed a conda_env file at https://github.com/nhamlv-55/Ropey/blob/master/conda_env.yaml so you can have the same environment as me. Note that there's a lot of redundancy in the conda_env, so I suggest you to cherry pick needed packages.
For the record, I was using pytorch 1.6 with cuda 10
Thanks!
