### ISSUE TITLE
No module named "Doping"

### ISSUE THREAD

**Issue by yogurt-shadow** [nhamlv-55/Ropey#6]
Hi, I cloned the repository and found a bug when trying to run it.

> File "/Ropey/RNN_train.py", line 3, in <module>
>     from Doping.pytorchtreelstm.treelstm import TreeLSTM, calculate_evaluation_orders
> ModuleNotFoundError: No module named 'Doping'

This seems a lack of Python package named **"Doping"**. Do you know how it install it? Directly pip install Doping doesn't work.

**Comment by XujieSi** [comment]
Hi @yogurt-shadow, nice to e-meet you here. The original name of this project was "Doping" but got renamed to "Ropey" at some point.
